version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/packages/entity-resolution"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/packages/network-drift"
    schedule:
      interval: "weekly"
